#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Linked demo (heatmap only).

Current capabilities:

- Loads a small dummy dataset generated by ``generate_demo_data.py`` using
  a pandas DataFrame for the heatmap.
- Uses a shared StateRegistry for global controls (metric radio + tag
  checkboxes).
- Creates a single Axes with a metric-switching, tag-filterable heatmap.
- Writes a self-contained HTML file that includes the controls and heatmap,
  and prints selector helpers + data snapshots to stdout.
"""

from pathlib import Path

import pandas as pd

from cssplt import plt
from cssplt.core.state import StateRegistry, TagFilterMode
from cssplt.plots.heatmap import HeatmapArtist


def _load_demo_data() -> dict[str, pd.DataFrame]:
    """Load demo CSVs produced by generate_demo_data.py."""
    data_dir = Path(__file__).resolve().parent / "data"
    heat = pd.read_csv(data_dir / "demo_heatmap.csv")
    kde = pd.read_csv(data_dir / "demo_kde.csv")
    radar = pd.read_csv(data_dir / "demo_radar.csv")
    return {"heatmap": heat, "kde": kde, "radar": radar}


if __name__ == "__main__":
    data = _load_demo_data()

    print("=== demo data shapes ===")
    for name, df in data.items():
        print(f"{name}: {df.shape[0]} rows x {df.shape[1]} cols")

    print("\n=== demo heatmap head ===")
    print(data["heatmap"].head())

    # Shared interactive state for the whole figure.
    # Tag filter semantics (coding-level, file-wide):
    # - TagFilterMode.ANY: show data with *any* selected tags (OR semantics)
    # - TagFilterMode.ALL: show data with *all* selected tags (AND semantics)
    state = StateRegistry(tag_filter_mode=TagFilterMode.ANY)
    metric = state.add_radio(
        "metric",
        ["accuracy", "latency", "cost"],
        default="accuracy",
    )
    tags = state.add_multi(
        "tag",
        ["none", "fast", "robust", "accurate", "cheap", "balanced"],
    )

    # Figure with a single heatmap subplot.
    fig = plt.figure(state=state)
    ax_heat = fig.add_subplot()

    # Heatmap with metric switching (Option B: pre-render one view per metric).
    heat_artist = HeatmapArtist(
        df=data["heatmap"],
        row="model",
        col="dataset",
        metric="accuracy",
    )
    heat_html, heat_css = heat_artist.render_html_views(
        metric_var_key="metric",
        metric_values=["accuracy", "latency", "cost"],
        tag_var=tags,
        tag_col="tag",
    )
    ax_heat.set_html(heat_html)
    ax_heat.set_extra_css(heat_css)


    out = Path(__file__).resolve().parent / "demo_linked.html"
    fig.write_html(str(out))
    print(f"\nWrote {out}")

    print("\n=== cssplt selector helpers ===")
    print("metric=accuracy:", metric.checked_selector("accuracy"))
    print("tags none (no selection):", tags.subset_selector([]))
    print("tags {fast}:", tags.subset_selector(["fast"]))
